# needed items for guild
# - item_id quantity
needed_items:
  - golden_apple 16
  - ender_pearl 16
  - book 64
  - diamond_block 8
  - brown_mushroom 16
  - amethyst_block 32
  - slime_ball 16

messages:
  not_enough_items_for_guild: "Gildia nie zostala utworzona - brak itemkow na gildie."
  invalid_command: "&cNiepoprawna komenda"
  not_enough_permissions: "&cBrak permisji!"
  server_error: "&cWystapil blad serwera! Skontaktuj sie z itedya, yuuki lub maksio lub sprobuj ponownie."
  invalid_usage: "&cZle uzycie komendy, zobacz pomoc."
  you_are_already_in_guild: "&eJestes juz w gildii!"
  guild_name_is_not_unique: "&eGildia o takiej nazwie juz istnieje! Wybierz inna."
  guild_short_name_is_not_unique: "&eGildia z takim skrotem juz istnieje! Wybierz inny."
  cuboid_intersection: "&eJakis cuboid juz istnieje na tym terenie (cuboid jest rozmiarow 150x150)!"
  you_dont_have_invite_to_guild: "&eNie masz zaproszenia do gildii!"
  welcome_to_guild: "&aWitamy w gildii &7[&e{GUILD_SHORT_NAME}&7] &e{GUILD_NAME}&a!"
  you_are_not_in_guild: "&eNie jestes w gildii!"
  you_have_to_be_owner_of_guild: "&eMusisz byc wlasicielem gildii zeby to zrobic!"
  deleted_guild: "&7Usunales gildie &e{GUILD_NAME}&7!"
  owner_can_only_delete_guild: "&aJestes wlascicielem gildii! Mozesz co najwyzej ja usunac."
  exit_from_guild: "&7Wyszedles z gildii &a{GUILD_NAME}&7!"
  player_doesnt_exist: "&eGracz {PLAYER_NAME} nie istnieje!"
  player_is_already_in_guild: "&eGracz {PLAYER_NAME} jest juz w gildii!"
  you_got_invite_message: "&aDostales zaproszenie do gildii &7[&e{GUILD_SHORT_NAME}&7] &e{GUILD_NAME} &aod gracza {PLAYER_NAME}. Aby zaakceptowac zaproszenie, wpisz /g akceptuj."
  invite_sent: "&aWyslano zaproszenie!"
  you_cant_kick_yourself: "&eNie mozesz wyrzucic sam siebie!"
  you_have_been_kicked_out_of_guild: "&eZostales wyrzucony z gildii {GUILD_NAME}!"
  you_kicked_out_a_user: "&aWyrzuciles uzytkownika {PLAYER_NAME}!"
  location_is_not_in_cuboid: "&eTa lokalizacja nie jest w cuboidzie twojej gildii!"
  you_cant_be_in_battle: "&eNie mozesz uzyc tej komendy podczas walki!"
  teleportation_in: "&6Teleportacja za {SECONDS} sekund..."
  moved_while_teleporting: "&eRuszyles sie! Teleportacja anulowana!"

  errors:
    golden_apple: "Potrzebujesz 16 zlotych jablek"
    ender_pearl: "Potrzebujesz 16 perel endu"
    book: "Potrzebujesz 64 ksiazki"
    diamond_block: "Potrzebujesz 8 blokow diamentu"
    brown_mushroom: "Potrzebujesz 16 grzybkow"
    amethyst_block: "Potrzebujesz 32 blokow ametystu"
    slime_ball: "Potrzebujesz 16 slime balli"